export const demoUsers = [
  {
    id: 1,
    name: "Sarah Chen",
    email: "sarah@example.com",
    role: "creator",
    publicKey: "GANG3GZKNCPZ5GX2HUQJTMUWJORQJ5XJMLLHFNNUW3GX4IHOGIF4IOXA",
    balance: 2450.5,
    xlmBalance: 1225.25,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: 2,
    name: "Alex Rodriguez",
    email: "alex@example.com",
    role: "creator",
    publicKey: process.env.DEMO_USER_2_PUBLIC_KEY || "GBVG2QOETF7PC7K4KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ3IJMRQ",
    balance: 1850.75,
    xlmBalance: 925.38,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  },
  {
    id: 3,
    name: "Jordan Kim",
    email: "jordan@example.com",
    role: "consumer",
    publicKey: process.env.DEMO_USER_3_PUBLIC_KEY || "GCZST3XVCDTUJ76ZAV2HA72KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ",
    balance: 500.0,
    xlmBalance: 250.0,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
  },
]

export const demoContent = [
  {
    id: 1,
    title: "React Advanced Patterns",
    creator: "Sarah Chen",
    creatorId: 1,
    price: 0.99,
    category: "Development",
    rating: 4.8,
    reviews: 245,
    views: 12500,
    image: "/react-tutorial.jpg",
    description: "Master advanced React patterns and best practices",
  },
  {
    id: 2,
    title: "UI Design Masterclass",
    creator: "Alex Rodriguez",
    creatorId: 2,
    price: 1.49,
    category: "Design",
    rating: 4.9,
    reviews: 189,
    views: 8900,
    image: "/design-course.jpg",
    description: "Learn professional UI design from scratch",
  },
  {
    id: 3,
    title: "Performance Optimization Guide",
    creator: "Sarah Chen",
    creatorId: 1,
    price: 0.79,
    category: "Development",
    rating: 4.7,
    reviews: 156,
    views: 6700,
    image: "/performance-guide.jpg",
    description: "Optimize your web applications for speed",
  },
  {
    id: 4,
    title: "TypeScript Complete Guide",
    creator: "Alex Rodriguez",
    creatorId: 2,
    price: 1.29,
    category: "Development",
    rating: 4.6,
    reviews: 203,
    views: 9200,
    image: "/typescript-tutorial.jpg",
    description: "Complete TypeScript guide for beginners to advanced",
  },
  {
    id: 5,
    title: "Next.js 16 Deep Dive",
    creator: "Sarah Chen",
    creatorId: 1,
    price: 1.99,
    category: "Development",
    rating: 4.9,
    reviews: 312,
    views: 15600,
    image: "/nextjs-guide.jpg",
    description: "Master Next.js 16 with App Router and Server Components",
  },
  {
    id: 6,
    title: "CSS Grid & Flexbox Mastery",
    creator: "Alex Rodriguez",
    creatorId: 2,
    price: 0.59,
    category: "Design",
    rating: 4.5,
    reviews: 128,
    views: 5400,
    image: "/css-tutorial.jpg",
    description: "Learn modern CSS layout techniques",
  },
]

export const demoTransactions = [
  {
    id: "tx_001",
    from: "GCZST3XVCDTUJ76ZAV2HA72KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ",
    to: "GBRPYHIL2CI3WHZDTOOQFC6EB4RRJC3XNRBF3LGYXMFNQ5BNHXVXVXV",
    amount: "0.99",
    contentId: 1,
    contentTitle: "React Advanced Patterns",
    timestamp: Date.now() - 7200000,
    status: "completed",
    hash: "abc123def456",
  },
  {
    id: "tx_002",
    from: "GCZST3XVCDTUJ76ZAV2HA72KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ",
    to: "GBVG2QOETF7PC7K4KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ3IJMRQ",
    amount: "1.49",
    contentId: 2,
    contentTitle: "UI Design Masterclass",
    timestamp: Date.now() - 18000000,
    status: "completed",
    hash: "ghi789jkl012",
  },
  {
    id: "tx_003",
    from: "GCZST3XVCDTUJ76ZAV2HA72KYQJJD6EXTQ5YWVDUZT4LAYJIY3FZEPWZ",
    to: "GBRPYHIL2CI3WHZDTOOQFC6EB4RRJC3XNRBF3LGYXMFNQ5BNHXVXVXV",
    amount: "0.79",
    contentId: 3,
    contentTitle: "Performance Optimization Guide",
    timestamp: Date.now() - 86400000,
    status: "completed",
    hash: "mno345pqr678",
  },
]
